version: 2.1
jobs:
  build_and_push:
    docker:
      - image: cimg/node:18.16.0
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build and Push Angular Docker Image
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            
            # ATTENTION : On pr√©cise le chemin vers le dossier angular ici
            docker build -t $DOCKER_USERNAME/angular-hello-world:latest ./angular
            
            docker push $DOCKER_USERNAME/angular-hello-world:latest

workflows:
  build_pipeline:
    jobs:
      - build_and_push
